// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frdoalhrweobdswvnbcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZG9hbGhyd2VvYmRzd3ZuYmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODYxODQsImV4cCI6MjA1ODg2MjE4NH0.7TilCaZJ8Z_COTgArcXMDs_fXa8BTsxWyanyS429Ybg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);